In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import pandas as pd
import numpy as np
data = pd.read_csv('/content/drive/MyDrive/soft computing/iris.data' , sep=",")
data.columns = ["1","2","3","4","5"]
data

1    2    3    4               5
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [ ]:
newData=data.drop("5",'columns')
print(newData)

       1    2    3    4
0    4.9  3.0  1.4  0.2
1    4.7  3.2  1.3  0.2
2    4.6  3.1  1.5  0.2
3    5.0  3.6  1.4  0.2
4    5.4  3.9  1.7  0.4
..   ...  ...  ...  ...
144  6.7  3.0  5.2  2.3
145  6.3  2.5  5.0  1.9
146  6.5  3.0  5.2  2.0
147  6.2  3.4  5.4  2.3
148  5.9  3.0  5.1  1.8

[149 rows x 4 columns]


<ipython-input-42-6a350c5a57bd>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  newData=data.drop("5",'columns')


In [ ]:
df_max_scaled = newData.copy()

for column in df_max_scaled.columns:
    if pd.api.types.is_numeric_dtype(df_max_scaled[column]):
        max_abs_value = df_max_scaled[column].abs().max()
        if max_abs_value != 0:
            df_max_scaled[column] = df_max_scaled[column] / max_abs_value
        else:
            df_max_scaled[column] = 0

display(df_max_scaled)


1         2         3     4
0    0.620253  0.681818  0.202899  0.08
1    0.594937  0.727273  0.188406  0.08
2    0.582278  0.704545  0.217391  0.08
3    0.632911  0.818182  0.202899  0.08
4    0.683544  0.886364  0.246377  0.16
..        ...       ...       ...   ...
144  0.848101  0.681818  0.753623  0.92
145  0.797468  0.568182  0.724638  0.76
146  0.822785  0.681818  0.753623  0.80
147  0.784810  0.772727  0.782609  0.92
148  0.746835  0.681818  0.739130  0.72

[149 rows x 4 columns]

In [ ]:

df_similarity = newData.copy()

num_objects = len(df_similarity)
similarity_matrix = np.zeros((num_objects, num_objects))

for i in range(num_objects):
    for j in range(num_objects):
        euclidean_distance = np.sqrt(((df_similarity.iloc[i] - df_similarity.iloc[j]) ** 2).sum())
        similarity_matrix[i, j] = euclidean_distance

print(similarity_matrix)


[[0.         0.3        0.33166248 ... 4.49888875 4.71805044 4.15331193]
 [0.3        0.         0.24494897 ... 4.66154481 4.84871117 4.29883705]
 [0.33166248 0.24494897 0.         ... 4.53321078 4.71911009 4.14969878]
 ...
 [4.49888875 4.66154481 4.53321078 ... 0.         0.6164414  0.64031242]
 [4.71805044 4.84871117 4.71911009 ... 0.6164414  0.         0.76811457]
 [4.15331193 4.29883705 4.14969878 ... 0.64031242 0.76811457 0.        ]]


In [ ]:
def create_similarity_matrix(df_max_scaled):
    m = df_max_scaled.shape[0]
    similarity_matrix = np.zeros((m, m))

    for i in range(m):
        for j in range(i + 1, m):
            dissimilarity = np.linalg.norm(df_max_scaled[i] - df_max_scaled[j])
            similarity_matrix[i, j] = dissimilarity
            similarity_matrix[j, i] = dissimilarity

    return similarity_matrix

# Assuming 'df_max_scaled' is a numpy array
df_max_scaled = df_max_scaled.to_numpy()

similarity_matrix = create_similarity_matrix(df_max_scaled)

m = len(similarity_matrix)

for i in range(m):
    for j in range(m):
        print(similarity_matrix[i][j], end=", ")
    print()


0.0, 0.054009985549707124, 0.04656871721974205, 0.13694988884467374, 0.2326692297013288, 0.10633221242975885, 0.09292326646085051, 0.06724802771814943, 0.048234519104084314, 0.17183051408092653, 0.09625410730198246, 0.04195510376884377, 0.09622195970464353, 0.25587446434711575, 0.34366331807941713, 0.22902980415035548, 0.12310217735488536, 0.21633995764119934, 0.18843782549230825, 0.11899827849393649, 0.18044633604474244, 0.15296325190686527, 0.14690147183686844, 0.11694311109138836, 0.031628948173851895, 0.12515931116981088, 0.1206869489148198, 0.0985217711990977, 0.059558360133795625, 0.03894764804457447, 0.13740549852120526, 0.2564217551181498, 0.28310505408843595, 0.048234519104084314, 0.05537604233839353, 0.13744660566648553, 0.048234519104084314, 0.06492925545502275, 0.09547473826367665, 0.1219979253115919, 0.17228943374167063, 0.07925858891264054, 0.1987803146769822, 0.21295485873360157, 0.04195510376884376, 0.18584653292170114, 0.05922999487396036, 0.16758176803884567, 0.069346

In [ ]:
def form_clusters(similarity_matrix):
    m = similarity_matrix.shape[0]
    clusters = []

    for i in range(m):
        # Calculate the average dissimilarity for the i-th object
        avg_dissimilarity = np.mean(similarity_matrix[i, :])

        # Form the cluster for the i-th object
        cluster = [i]  # Initialize the cluster with the i-th object

        # Add objects to the cluster if their dissimilarity is less than the average similarity
        for j in range(m):
            if i != j and similarity_matrix[i, j] < avg_dissimilarity:
                cluster.append(j)

        clusters.append(cluster)  # Add the formed clusters to the list of clusters

    return clusters

clusters = form_clusters(similarity_matrix)

# Print the clusters
for i, cluster in enumerate(clusters):
    print(f"Cluster {i+1}: {cluster}")

Cluster 1: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 56, 59, 61, 63, 66, 68, 78, 79, 80, 81, 91, 92, 94, 97]
Cluster 2: [1, 0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 56, 59, 61, 63, 66, 68, 78, 79, 80, 81, 92, 97]
Cluster 3: [2, 0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 56, 59, 61, 63, 66, 68, 78, 79, 80, 81, 91, 92, 94, 97]
Cluster 4: [3, 0, 1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 56, 59, 63, 66, 68, 78, 79, 80, 81, 92, 97]
Clus

In [ ]:
def is_subset(cluster_a, cluster_b):
    return set(cluster_a).issubset(set(cluster_b))

def remove_subsets(clusters):
    sorted_clusters = sorted(clusters, key=len, reverse=True)
    non_subset_clusters = []

    for cluster in sorted_clusters:
        is_subset_flag = False
        for non_subset_cluster in non_subset_clusters:
            if is_subset(cluster, non_subset_cluster):
                is_subset_flag = True
                break

        # If the current cluster is not a subset, add it to the final list
        if not is_subset_flag:
            non_subset_clusters.append(cluster)

    return non_subset_clusters

# Assuming 'clusters' contains the clusters formed earlier
p_clusters = remove_subsets(clusters)

# Print the non-subset clusters
for i, cluster in enumerate(p_clusters):
    print(f"Cluster {i+1}: {cluster}")



Cluster 1: [112, 49, 50, 51, 52, 53, 54, 55, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148]
Cluster 2: [82, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 109, 110, 111, 112, 113, 114, 115, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148]
Cluster 3: [40, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 

In [ ]:
def calculate_similarity(cluster_a, cluster_b):
    intersection = len(set(cluster_a).intersection(set(cluster_b)))
    union = len(set(cluster_a).union(set(cluster_b)))
    return intersection / union

def create_similarity_matrix(clusters):
    p = len(clusters)
    similarity_matrix = np.zeros((p, p))

    for i in range(p):
        for j in range(p):
            similarity_matrix[i, j] = calculate_similarity(clusters[i], clusters[j])

    return similarity_matrix

# Assuming you have 'p_clusters' as the result from step A
similarity_matrix = create_similarity_matrix(p_clusters)

# Print the similarity matrix
print("Similarity Matrix :")
print(similarity_matrix)

Similarity Matrix :
[[1.         0.95       0.14765101 0.14765101 0.49090909 0.57692308
  0.52336449 0.56862745 0.58415842]
 [0.95       1.         0.15862069 0.15862069 0.51886792 0.61
  0.55339806 0.60204082 0.6185567 ]
 [0.14765101 0.15862069 1.         0.97260274 0.31730769 0.24545455
  0.28301887 0.23148148 0.22018349]
 [0.14765101 0.15862069 0.97260274 1.         0.31730769 0.24545455
  0.28301887 0.23148148 0.22018349]
 [0.49090909 0.51886792 0.31730769 0.31730769 1.         0.83098592
  0.92537313 0.82608696 0.8       ]
 [0.57692308 0.61       0.24545455 0.24545455 0.83098592 1.
  0.86956522 0.90909091 0.90909091]
 [0.52336449 0.55339806 0.28301887 0.28301887 0.92537313 0.86956522
  1.         0.89393939 0.86567164]
 [0.56862745 0.60204082 0.23148148 0.23148148 0.82608696 0.90909091
  0.89393939 1.         0.96774194]
 [0.58415842 0.6185567  0.22018349 0.22018349 0.8        0.90909091
  0.86567164 0.96774194 1.        ]]


In [ ]:
def merge_clusters(cluster_a, cluster_b):
    return list(set(cluster_a).union(set(cluster_b)))

def find_most_similar_clusters(similarity_matrix):
    p = similarity_matrix.shape[0]
    max_similarity = 0
    most_similar_clusters = (0, 0)

    for i in range(p):
        for j in range(i + 1, p):
            if similarity_matrix[i, j] > max_similarity:
                max_similarity = similarity_matrix[i, j]
                most_similar_clusters = (i, j)

    return most_similar_clusters

# Find the most similar clusters
most_similar_clusters = find_most_similar_clusters(similarity_matrix)
cluster_k, cluster_l = most_similar_clusters

# Merge the most similar clusters
new_cluster = merge_clusters(p_clusters[cluster_k], p_clusters[cluster_l])

print(f"Merged Cluster: {new_cluster}")

IndexError: ignored

In [ ]:
desired_num_clusters = 5 # Replace K with your desired number of clusters

while len(p_clusters) > desired_num_clusters:
    # Step 3A: Remove clusters that are subsets of others
    p_clusters = remove_subsets(p_clusters)

    # Step 3B: Create similarity matrix C
    similarity_matrix_C = create_similarity_matrix(p_clusters)

    # Step 3C: Find most similar clusters, merge them, and update p_clusters
    most_similar_clusters = find_most_similar_clusters(similarity_matrix)
    cluster_k, cluster_l = most_similar_clusters

    # Merge the most similar clusters
    new_cluster = merge_clusters(p_clusters[cluster_k], p_clusters[cluster_l])

    # Remove the merged clusters from the list
    p_clusters.pop(cluster_k)
    if cluster_l > cluster_k:
        cluster_l -= 1  # Adjust index after removal of previous cluster
    p_clusters.pop(cluster_l)

    # Add the new merged cluster to the list
    p_clusters.append(new_cluster)


# Print the final merged clusters
for i, cluster in enumerate(p_clusters):
    print(f"Final Cluster {i+1}: {cluster}")

Final Cluster 1: [22, 24, 25, 30, 40, 42, 44, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148]
Final Cluster 2: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 70, 71, 72, 73, 74, 75, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 105, 118, 122, 125, 132, 133, 137]
